site_name: Be Moore Homelab

theme:
    name: 'material'
    palette:

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode


# Extensions
markdown_extensions:
  - pymdownx.highlight
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

nav:
  - Introduction: 'README.md'
  - 'Docker.md'
  - 'Dashy.md'
  - 'HomeAssistant.md'
  - 'NTFY.md'
  - 'PiHole.md'
  - 'Portainer.md'
  - 'Traefik.md'
  - 'Uptime Kuma.md'
  - 'VMWare ESXi.md'
  - 'Rick': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1'
exclude_docs: |
  .gitignore
  mkdocks.yml

plugins:
  - search
  - roamlinks 